### ISSUE TITLE
Error when running sync-all.sh

### ISSUE THREAD

**Issue by redstarinternet** [jasperf/trellis-sync#3]
Running the script returns:

`scripts/sync-all.sh: 25: scripts/sync-all.sh: Syntax error: "(" unexpected (expecting "then")`

**Comment by jasperf** [comment]
What OS/terminal were you using? Also see http://stackoverflow.com/questions/18155852/syntax-error-end-of-file-unexpected-expecting-then#18157255

**Comment by redstarinternet** [comment]
I'm using ubuntu 16.04 and gnome terminal. I tried using dos2unix on the scripts as described in the link above but I still get the same error.

**Comment by jasperf** [comment]
Well, what about the more direct approach using `sed -i 's/\r$//' filename`?

**Comment by redstarinternet** [comment]
Just tried that with the same result. I've also tried:
- Only editing the files with gedit rather than vim
- Using both zsh and bash

**Comment by jasperf** [comment]
Try checking it with : http://www.shellcheck.net/ . And or try newline before `then` on that line 25. Also read http://unix.stackexchange.com/questions/48786/how-can-i-test-for-posix-compliance-for-shell-scripts#48787 as it may be related.

**Comment by redstarinternet** [comment]
Shellcheck output:
```
Line 23:
read -r -p "Would you really like to reset the $TO database and sync $DIR from $FROM? [y/N] " response
        ^-- SC2039: In POSIX sh, read -p is undefined.
 
Line 25:
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
   ^-- SC2039: In POSIX sh, [[ ]] is undefined.
```

I've checked that thread but not sure where to go from here. I've tried adding a newline before 'then' :(

**Comment by jasperf** [comment]
Try `#!/bin/bash` instead of `#!/bin/sh` See https://github.com/koalaman/shellcheck/wiki/SC2039 as well as https://wiki.ubuntu.com/DashAsBinSh

**Comment by redstarinternet** [comment]
That did it, issue closed. Many thanks :)

**Comment by s3w47m88** [comment]
I'm getting the same error but changing from sh to bash didn't matter.

**Comment by jasperf** [comment]
@s3w47m88 To reopen this ticket I will need some more information on what OS you are using, what terminal, what was done to produce this and the exact error report.
